# Generated by Django 2.1.1 on 2018-10-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('perspective_id', models.IntegerField()),
                ('evidence_id', models.IntegerField()),
                ('comment', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HITSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('instruction_complete', models.BooleanField(default=False)),
                ('job_complete', models.BooleanField(default=False)),
                ('jobs', models.TextField()),
                ('finished_jobs', models.TextField()),
                ('duration', models.DurationField()),
                ('last_start_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perspective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PerspectiveRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('claim_id', models.IntegerField()),
                ('perspective_id', models.IntegerField()),
                ('rel', models.CharField(choices=[('S', 'Support'), ('U', 'Undermine'), ('I', 'Irrelevant'), ('N', 'Not Sure')], max_length=1)),
                ('comment', models.TextField(null=True)),
            ],
        ),
    ]
