# Generated by Django 2.1.1 on 2018-10-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='assignment_counts',
            field=models.IntegerField(default=0),
        ),
    ]
