# Generated by Django 2.1.1 on 2018-10-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_claim_assignment_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='finished_counts',
            field=models.IntegerField(default=0),
        ),
    ]
