# Generated by Django 2.1.1 on 2018-10-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_claim_finished_counts'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hit_session_id', models.IntegerField()),
                ('author', models.CharField(max_length=100)),
                ('perspective_id', models.IntegerField()),
                ('evidence_id', models.IntegerField()),
                ('obfuscation_choices', models.TextField()),
                ('user_choice', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceHITSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('instruction_complete', models.BooleanField(default=False)),
                ('job_complete', models.BooleanField(default=False)),
                ('jobs', models.TextField()),
                ('finished_jobs', models.TextField()),
                ('duration', models.DurationField()),
                ('last_start_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='claim',
            name='evidence_assign_counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='claim',
            name='evidence_finished_counts',
            field=models.IntegerField(default=0),
        ),
    ]
