# Generated by Django 2.1.1 on 2018-10-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20181026_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='perspective',
            name='pilot1_high_agreement',
            field=models.BooleanField(default=False),
        ),
    ]
