# Generated by Django 2.1.1 on 2018-11-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_perspective_pilot1_high_agreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquivalenceAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField()),
                ('author', models.CharField(max_length=100)),
                ('perspective_id', models.IntegerField()),
                ('user_choice', models.TextField(default='[]')),
            ],
        ),
        migrations.RenameModel(
            old_name='EvidenceHITSession',
            new_name='EquivalenceHITSession',
        ),
        migrations.DeleteModel(
            name='EvidenceAnnotation',
        ),
        migrations.RenameField(
            model_name='claim',
            old_name='evidence_assign_counts',
            new_name='equivalence_assign_counts',
        ),
        migrations.RenameField(
            model_name='claim',
            old_name='evidence_finished_counts',
            new_name='equivalence_finished_counts',
        ),
    ]
