# Generated by Django 2.1.1 on 2018-11-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20181101_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='perspective',
            name='similar_persps',
            field=models.TextField(default='[]'),
        ),
    ]
