# Generated by Django 2.1.1 on 2018-11-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_perspective_similar_persps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perspectiverelation',
            name='rel',
            field=models.CharField(choices=[('S', 'Support'), ('U', 'Undermine'), ('A', 'Slight Support'), ('B', 'Slight Undermine'), ('N', 'Not Sure')], max_length=1),
        ),
    ]
