# Generated by Django 2.1.1 on 2018-11-25 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_evidencehitsession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='equivalence_assign_counts',
            new_name='evidence_assign_counts',
        ),
        migrations.RenameField(
            model_name='claim',
            old_name='equivalence_finished_counts',
            new_name='evidence_finished_counts',
        ),
    ]
