# Generated by Django 2.1.1 on 2018-11-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20181125_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_ids', models.TextField(default='[]')),
                ('assign_counts', models.IntegerField(default=0)),
                ('finished_counts', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='evidence',
            name='persp_candidates',
            field=models.TextField(default='[]'),
        ),
    ]
