# Generated by Django 2.1.1 on 2018-11-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20181126_0742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidence',
            old_name='persp_candidates',
            new_name='origin_candidates',
        ),
        migrations.AddField(
            model_name='evidencerelation',
            name='anno',
            field=models.CharField(choices=[('S', 'Supported'), ('N', 'Not_Supported')], default='S', max_length=1),
        ),
    ]
