# Generated by Django 2.1.1 on 2018-11-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20181126_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='google_candidates',
            field=models.TextField(default='[]'),
        ),
    ]
