# Generated by Django 2.1.1 on 2018-11-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20181127_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restep1results',
            name='label_3',
            field=models.CharField(choices=[('S', 'Support'), ('U', 'Undermine'), ('N', 'Not Valid'), ('D', 'Doesnt have Majority Vote')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='restep1results',
            name='label_5',
            field=models.CharField(choices=[('S', 'Support'), ('U', 'Undermine'), ('A', 'Slight Support'), ('B', 'Slight Undermine'), ('N', 'Not Valid'), ('D', 'Doesnt have Majority Vote')], default='D', max_length=1),
        ),
    ]
