# Generated by Django 2.1.1 on 2018-11-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_claim_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step3Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perspective_id', models.IntegerField()),
                ('evidence_id', models.IntegerField()),
                ('vote_support', models.IntegerField(default=0)),
                ('vote_not_support', models.IntegerField(default=0)),
                ('p_i', models.FloatField(default=0)),
                ('label', models.CharField(choices=[('S', 'Support'), ('N', 'Not Support'), ('D', 'Doesnt have Majority Vote')], default='D', max_length=1)),
            ],
        ),
    ]
