# Generated by Django 2.1.1 on 2018-11-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_step3results'),
    ]

    operations = [
        migrations.AddField(
            model_name='perspective',
            name='more_than_two_tokens',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perspective',
            name='pilot1_have_stance',
            field=models.BooleanField(default=False),
        ),
    ]
