# Generated by Django 2.1.1 on 2018-12-01 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20181130_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerspectiveParaphraseHints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perspective_id', models.IntegerField()),
                ('content', models.TextField()),
                ('lucene_score', models.FloatField()),
            ],
        ),
    ]
