# Generated by Django 2.1.1 on 2018-12-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20181130_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParaphraseBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perspective_ids', models.TextField(default='[]')),
                ('assign_counts', models.IntegerField(default=0)),
                ('finished_counts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ParaphraseHITSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('instruction_complete', models.BooleanField(default=False)),
                ('job_complete', models.BooleanField(default=False)),
                ('jobs', models.TextField()),
                ('finished_jobs', models.TextField()),
                ('duration', models.DurationField()),
                ('last_start_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerspectiveParaphrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perspective_id', models.IntegerField()),
                ('user_generated', models.TextField(default='[]')),
                ('session_ids', models.TextField(default='[]')),
                ('hints', models.TextField(default='[]')),
            ],
        ),
    ]
