# Generated by Django 2.1.1 on 2018-12-01 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_paraphrasebatch_paraphrasehitsession_perspectiveparaphrase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paraphrasebatch',
            old_name='perspective_ids',
            new_name='paraphrase_ids',
        ),
    ]
