# Generated by Django 2.1.1 on 2018-12-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_auto_20181201_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquivalenceBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perspective_ids', models.TextField(default='[]')),
                ('assign_counts', models.IntegerField(default=0)),
                ('finished_counts', models.IntegerField(default=0)),
            ],
        ),
    ]
