# Generated by Django 2.1.1 on 2018-12-07 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_topichitsession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='evidence_assign_counts',
            new_name='topic_assign_counts',
        ),
        migrations.RenameField(
            model_name='claim',
            old_name='evidence_finished_counts',
            new_name='topic_finished_counts',
        ),
    ]
