# Generated by Django 2.1.1 on 2018-12-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_topicannotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('annotation', models.TextField()),
            ],
        ),
    ]
