# Generated by Django 2.1.1 on 2018-12-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_humanannotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanannotation',
            name='claim_id',
            field=models.IntegerField(default=0),
        ),
    ]
